runtime: nodejs18.x

env:
  NEXT_PUBLIC_API_URL: https://api.lexlucglobal.ng/api/v1
  NEXT_PUBLIC_SITE_URL: https://www.lexlucglobal.ng
  NEXT_PUBLIC_SITE_NAME: Lexluc Global Services

build_command: npm run build
start_command: npm run start

envPath:
  - .env.production
